set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER admin;
ALTER USER admin WITH PASSWORD 'admin';
GRANT ALL ON DATABASE "$POSTGRES_DB" TO admin;
GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO admin;
GRANT ALL PRIVILEGES ON SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
EOSQL